import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { useCallback } from "react"
import { useRouter } from "next/router"
import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"

import { signUpSchema, ISignUp } from "../../utils/authValidation"
import { trpc } from "../../utils/trpc"

const NewUser: NextPage = () => {
  const router = useRouter()
  const { register, handleSubmit } = useForm<ISignUp>({
    resolver: zodResolver(signUpSchema),
  })
  const { mutateAsync } = trpc.auth.signUp.useMutation()

  const onSubmit = useCallback(
    async (data: ISignUp) => {
      const result = await mutateAsync(data)
      if ((result.status = 201)) {
        router.push("/")
      }
    },
    [mutateAsync, router]
  )
  return (
    <div>
      <Head>
        <title>Registration</title>
        <meta name="description" content="generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form
          className="flex h-screen w-full items-center justify-center"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="w-96 bg-blue-100 shadow-xl">
            <div className="card-body">
              <h2>Create an accouunt!</h2>
              <input
                type="text"
                placeholder="Username"
                className="my-2 w-full max-w-xs"
                {...register("name")}
              />
              <input
                type="email"
                placeholder="Type your email..."
                className="input input-bordered w-full max-w-xs"
                {...register("email")}
              />
              <input
                type="password"
                placeholder="Type your password..."
                className="input input-bordered my-2 w-full max-w-xs"
                {...register("password")}
              />
              <div className="card-actions items-center justify-between">
                <Link href="/" className="link">
                  Go to login
                </Link>
                <button
                  className="btn btn-secondary border drop-shadow-2xl"
                  type="submit"
                >
                  Sign Up
                </button>
              </div>
            </div>
          </div>
        </form>
      </main>
    </div>
  )
}

export default NewUser